theme: jekyll-theme-hacker
permalink: /:slug

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: NarveyPages
title: NarveyPages

# Short description (goes below the title; it will also be used in the RSS feed)
description: temp name for Nathan’s Code Samples and Projects

# Your name, as you want it to appear underneath each post and in the footer
#author: Your Name

# Your email if you want it to be linked on the contact page
#author_email: you@example.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /cat/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# How many articles do you wish to appear on the front page:
# paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [LICENSE, README.markdown, package.json, node_modules]

#### YAML Front Matter defaults #####
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      #slug: how could I possibly default a slug?
      title: {{ page.slug }}
